
package Vista;

import Modelo.ColorDao;
import Modelo.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ColoresView extends javax.swing.JFrame {

    ColorDao colorDao = new ColorDao();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public ColoresView() {
        initComponents();
        setLocationRelativeTo(null);
        listarColores();
        txtIdColor.setVisible(false);
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreColor = new javax.swing.JTextField();
        txtIdColor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnGuardarColor = new javax.swing.JButton();
        btnActualizarColor = new javax.swing.JButton();
        btnNuevoColor = new javax.swing.JButton();
        btnEliminarColor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaColores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Colores");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Color:");

        txtNombreColor.setMinimumSize(new java.awt.Dimension(120, 35));
        txtNombreColor.setPreferredSize(new java.awt.Dimension(120, 25));

        btnGuardarColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo24.png"))); // NOI18N
        btnGuardarColor.setText("Guardar");
        btnGuardarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarColor);

        btnActualizarColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar24.png"))); // NOI18N
        btnActualizarColor.setText("Actualizar");
        btnActualizarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarColor);

        btnNuevoColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnNuevoColor.setText("Nuevo");
        btnNuevoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoColor);

        btnEliminarColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_25x25.png"))); // NOI18N
        btnEliminarColor.setText("Borrar");
        btnEliminarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarColor);

        tablaColores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Color"
            }
        ));
        tablaColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaColoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaColores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreColor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarColorActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreColor.getText();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre");
            return;
        }

        Color color = new Color();
        color.setNombre(nombre);

        if (colorDao.Registrar(color)) {
            listarColores();
            limpiar();
        }
    }//GEN-LAST:event_btnGuardarColorActionPerformed

    private void btnActualizarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarColorActionPerformed
        // TODO add your handling code here:

        if (txtIdColor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        Color color = new Color();
        color.setId(Integer.parseInt(txtIdColor.getText()));
        color.setNombre(txtNombreColor.getText());

        if (colorDao.Modificar(color)) {
            listarColores();
            limpiar();
        }
    }//GEN-LAST:event_btnActualizarColorActionPerformed

    private void tablaColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaColoresMouseClicked
        // TODO add your handling code here:

        int fila = tablaColores.rowAtPoint(evt.getPoint());

        txtIdColor.setText(tablaColores.getValueAt(fila, 0).toString());
        txtNombreColor.setText(tablaColores.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablaColoresMouseClicked

    private void btnNuevoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoColorActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnNuevoColorActionPerformed

    private void btnEliminarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarColorActionPerformed
        // TODO add your handling code here:
        if (txtIdColor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        int id = Integer.parseInt(txtIdColor.getText());

        if (colorDao.Eliminar(id)) {
            listarColores();
            limpiar();
        }
        
    }//GEN-LAST:event_btnEliminarColorActionPerformed
    //txtIdColor.setVisible(false);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarColor;
    private javax.swing.JButton btnEliminarColor;
    private javax.swing.JButton btnGuardarColor;
    private javax.swing.JButton btnNuevoColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaColores;
    private javax.swing.JTextField txtIdColor;
    private javax.swing.JTextField txtNombreColor;
    // End of variables declaration//GEN-END:variables

public void listarColores() {
    modelo = (DefaultTableModel) tablaColores.getModel();
    modelo.setRowCount(0);

    for (Color color : colorDao.Listar()) {
        modelo.addRow(new Object[]{color.getId(), color.getNombre()});
    }
}



private void limpiar() {
    txtIdColor.setText("");
    txtNombreColor.setText("");
}


}
