 package Vista;


import Modelo.Pago;
import Modelo.TipoPago;
import Modelo.Config;
import Modelo.ConfigDao;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class DialogoPagos extends javax.swing.JDialog {

    private BigDecimal totalVenta;
    private BigDecimal totalPagado = BigDecimal.ZERO;
    private BigDecimal montoBruto = BigDecimal.ZERO;
    private BigDecimal saldo;
    private List<Pago> pagos = new ArrayList<>();

    private ConfigDao confDao = new ConfigDao();

    /**
     * Creates new form DialogPagos
     */
    public DialogoPagos(java.awt.Frame parent, BigDecimal totalVenta) {
        super(parent, true); // modal SIEMPRE
        this.totalVenta = totalVenta;
        this.saldo = totalVenta;
        //this.montoBruto = totalVenta;

        initComponents();
        this.setLocationRelativeTo(null);
        cmbTipoPago.setModel(
                new DefaultComboBoxModel<>(TipoPago.values())
        );

        cargarTiposPago();
        actualizarTotales();
        
    }
        /*=====ZONA DE GETTERS=====*/
    
    public List<Pago> getPagos() {
        return pagos;
    }
    
    public BigDecimal getTotalPagado() {
        return totalPagado;
    }

    public BigDecimal getTotalVenta() {
        return totalVenta;
    }

    public BigDecimal getMontoBruto() {
        return montoBruto;
    }
    
    
        /*=====FIN ZONA DE GETTERS=====*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalVenta = new javax.swing.JLabel();
        lblTotalPagado = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnAgregarPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        cmbTipoPago = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        lblTotalCancelado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de Pago");
        setModal(true);

        lblTotalVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalVenta.setText("TOTAL DE LA VENTA:");

        lblTotalPagado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPagado.setText("TOTAL PAGADO:");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSaldo.setText("SALDO:");

        btnFinalizar.setText("Finalizar Compra");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnAgregarPago.setText("✔ AGREGAR");
        btnAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPagoActionPerformed(evt);
            }
        });

        jLabel1.setText("FORMA DE PAGO:");

        jLabel2.setText("MONTO:");

        txtMonto.setMinimumSize(new java.awt.Dimension(80, 22));
        txtMonto.setPreferredSize(new java.awt.Dimension(80, 22));

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Monto Bruto", "Descuento", "Monto Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        btnEliminar.setText("❌ ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTotalCancelado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalCancelado.setText("TOTAL CANCELADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCancelado)
                    .addComponent(lblSaldo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFinalizar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarPago)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTotalPagado)
                            .addComponent(lblTotalVenta)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalVenta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPago)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalPagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCancelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo)
                .addGap(4, 4, 4)
                .addComponent(btnFinalizar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPagoActionPerformed
        // TODO add your handling code here:
     
    if (txtMonto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un monto");
        return;
    }

    BigDecimal monto;
    try {
        monto = new BigDecimal(txtMonto.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Monto inválido");
        return;
    }

    if (monto.compareTo(BigDecimal.ZERO) <= 0) {
        JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero");
        return;
    }

    TipoPago tipo = (TipoPago) cmbTipoPago.getSelectedItem();

    // ❗ VALIDACIÓN CORRECTA: contra saldo
    if (monto.compareTo(saldo) > 0) {
        JOptionPane.showMessageDialog(this, "El monto supera el saldo pendiente");
        return;
    }

    // ✅ CREAR PAGO
    Pago pago = crearPago(tipo, monto);

    // ✅ AGREGAR A LISTA
    pagos.add(pago);

    // ✅ ACUMULAR CORRECTAMENTE
    montoBruto = montoBruto.add(pago.getMontoBruto());
    totalPagado = totalPagado.add(pago.getMontoFinal());

    // ✅ RECALCULAR SALDO (SIEMPRE CON MONTO BRUTO)
    saldo = totalVenta.subtract(montoBruto);

    // ✅ MOSTRAR EN TABLA
    agregarPagoATabla(pago);

    // ✅ ACTUALIZAR LABELS
    actualizarTotales();

    txtMonto.setText("");



    
    }//GEN-LAST:event_btnAgregarPagoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

     // Verificar si la lista de pagos no está vacía
    if (pagos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar al menos un pago");
        return;
    }

    // Verificar que el total pagado sea suficiente (o igual) al total de la venta
    if (montoBruto.compareTo(totalVenta) < 0) {
        JOptionPane.showMessageDialog(this, "El monto pagado no cubre el total de la venta");
        return;
    }

    // Verificar que no haya un pago mayor al total de la venta
    if (totalPagado.compareTo(totalVenta) > 0) {
        JOptionPane.showMessageDialog(this, "El monto pagado excede el total de la venta. No se permite el vuelto.");
        return;
    }

    // Si todas las validaciones pasan, cerramos el diálogo
    this.dispose();


    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
    int fila = tblPagos.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un pago para eliminar");
        return;
    }

    // Obtener el pago desde la lista
    Pago p = pagos.get(fila);

    // Restar montos
    montoBruto = montoBruto.subtract(p.getMontoBruto());
    totalPagado = totalPagado.subtract(p.getMontoFinal());

    // Eliminar de la lista
    pagos.remove(fila);

    // Eliminar de la tabla
    DefaultTableModel modelo = (DefaultTableModel) tblPagos.getModel();
    modelo.removeRow(fila);

    // Recalcular totales
    actualizarTotales();

    
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPago;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<TipoPago> cmbTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTotalCancelado;
    private javax.swing.JLabel lblTotalPagado;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JTable tblPagos;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
  
    private void cargarTiposPago() {
        cmbTipoPago.removeAllItems();
        cmbTipoPago.addItem(TipoPago.EFECTIVO);
        cmbTipoPago.addItem(TipoPago.TRANSFERENCIA);
        cmbTipoPago.addItem(TipoPago.CREDITO);
    }


private void actualizarTotales() {

    if (totalVenta == null) totalVenta = BigDecimal.ZERO;
    if (totalPagado == null) totalPagado = BigDecimal.ZERO;
    if (montoBruto == null) montoBruto = BigDecimal.ZERO;

    saldo = totalVenta.subtract(montoBruto);

    lblTotalVenta.setText("Total venta: $" + totalVenta);
    lblTotalPagado.setText("Total pagado: $" + montoBruto);
    lblTotalCancelado.setText("Total cobrado: $" + totalPagado);
    lblSaldo.setText("Saldo: $" + saldo);
}



    private Pago crearPago(TipoPago tipo, BigDecimal montoBruto) {

        BigDecimal porcentaje = obtenerPorcentajeDescuento(tipo);
        BigDecimal descuento = montoBruto
                .multiply(porcentaje)
                .divide(new BigDecimal("100"));

        BigDecimal montoFinal = montoBruto.subtract(descuento);

        Pago p = new Pago();
        p.setTipo(tipo);
        p.setMontoBruto(montoBruto);
        p.setDescuento(descuento);
        p.setMontoFinal(montoFinal);

        return p;
    }
    
    private BigDecimal obtenerPorcentajeDescuento(TipoPago tipo) {

        Config conf = confDao.obtenerConfig();

        switch (tipo) {
            case EFECTIVO:
                return conf.getEfectivo();
            case TRANSFERENCIA:
                return conf.getTransferencia();
            case CREDITO:
                return conf.getCredito();
            default:
                return BigDecimal.ZERO;
        }
    }
   
    private void agregarPagoATabla(Pago p) {

        DefaultTableModel modelo = (DefaultTableModel) tblPagos.getModel();

        modelo.addRow(new Object[]{
            p.getTipo(),
            p.getMontoBruto(),
            p.getDescuento(),
            p.getMontoFinal()
        });
    }
  

}
