
package Vista;
import com.google.gson.reflect.TypeToken;
import com.google.gson.Gson;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.util.List;
import java.io.File;
import java.lang.reflect.Type;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import Modelo.ProductosDao;
import Modelo.Config;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class VerStock extends javax.swing.JFrame {

    /**
     * Creates new form VerStock
     */
    
    public VerStock() {
        initComponents();
         //setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        this.setLocationRelativeTo(null);
    }
    


private void cargarDatosDesdeJSON() {
    
    Config C = new Config();
    ProductosDao PD = new ProductosDao();
    C = PD.BuscarDatos();
    String Path = C.getEntrada();
    //JOptionPane.showMessageDialog(null,Path);
    try {
        FileReader reader = new FileReader( Path/*"C:\\Users\\feder\\Mi unidad\\Json\\stock.json"*/);
        Gson gson = new Gson();

        // Leer el objeto completo
        JsonObject jsonObject = gson.fromJson(reader, JsonObject.class);

        // Extraer el array de items
        JsonArray items = jsonObject.getAsJsonArray("items");

        // Limpiar tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaStock.getModel();
        modelo.setRowCount(0);

        // Cargar cada producto en la tabla
        for (int i = 0; i < items.size(); i++) {
            JsonObject item = items.get(i).getAsJsonObject();

            modelo.addRow(new Object[]{
                i + 1, // ID generado automáticamente
                item.get("codigo").getAsString(),
                item.get("descripcion").getAsString(),
                item.get("precio").getAsDouble(),
                item.get("stock").getAsInt()
            });
        }

        reader.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al leer JSON: " + e.getMessage());
    }
}
private void buscarEnTablaStock(String textoBusqueda) {
    Config C = new Config();
    ProductosDao PD = new ProductosDao();
    C = PD.BuscarDatos();
    String Path = C.getEntrada();

    try {
        FileReader reader = new FileReader(Path);
        Gson gson = new Gson();

        JsonObject jsonObject = gson.fromJson(reader, JsonObject.class);
        JsonArray items = jsonObject.getAsJsonArray("items");

        DefaultTableModel modelo = (DefaultTableModel) tablaStock.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (int i = 0; i < items.size(); i++) {
            JsonObject item = items.get(i).getAsJsonObject();
            String codigo = item.get("codigo").getAsString().toLowerCase();
            String descripcion = item.get("descripcion").getAsString().toLowerCase();

            if (codigo.contains(textoBusqueda.toLowerCase()) || 
                descripcion.contains(textoBusqueda.toLowerCase())) {

                modelo.addRow(new Object[]{
                    i + 1,
                    item.get("codigo").getAsString(),
                    item.get("descripcion").getAsString(),
                    item.get("precio").getAsDouble(),
                    item.get("stock").getAsInt()
                });
            }
        }

        reader.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar en JSON: " + e.getMessage());
    }
}


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelBuscarStock = new javax.swing.JLabel();
        txtBuscarStock = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        panelCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        panelLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        panelCabecera.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(142, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(142, 25));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        labelBuscarStock.setBackground(new java.awt.Color(255, 255, 255));
        labelBuscarStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelBuscarStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa24.png"))); // NOI18N
        labelBuscarStock.setText("Buscar");
        jPanel1.add(labelBuscarStock);

        txtBuscarStock.setMinimumSize(new java.awt.Dimension(150, 22));
        txtBuscarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarStockActionPerformed(evt);
            }
        });
        txtBuscarStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarStockKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarStock);

        panelCabecera.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 270, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descarga-en-la-nube (24x24).png"))); // NOI18N
        jButton3.setText("Consultar");
        jButton3.setAlignmentY(0.0F);
        jButton3.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButton3.setMaximumSize(new java.awt.Dimension(125, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(125, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(125, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelCabecera.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 120, 30));

        getContentPane().add(panelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaStock);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarStockActionPerformed
        // TODO add your handling code here:
        buscarEnTablaStock(txtBuscarStock.getText());
    }//GEN-LAST:event_txtBuscarStockActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cargarDatosDesdeJSON();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarStockKeyReleased
        // TODO add your handling code here:
         buscarEnTablaStock(txtBuscarStock.getText());
    }//GEN-LAST:event_txtBuscarStockKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscarStock;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField txtBuscarStock;
    // End of variables declaration//GEN-END:variables
}
